name: "🐞 Bug Report"
description: "Create a generic bug report against a package."
title: "[BUG]: "
labels: ["type::bug"]
body:
  - type: "dropdown"
    id: "version"
    attributes:
      label: "BlackArch version"
      description: |
        What version of BlackArch are you using?
      options:
        - "Please select a version."
        - "- BlackArch Linux 64 bit Full ISO 2023.04.01"
        - "- BlackArch Linux 64 bit Slim ISO 2023.05.01"
        - "- BlackArch Linux 64 bit Netinstall ISO 2023.04.01"
        - "- BlackArch Linux 64 bit OVA Image 2023.04.01"
        - "- BlackArch Linux Docker Image"
      default: 0
    validations:
      required: true

