name: "🐞 Bug Report"
description: "Create a generic bug report against a package."
title: "[BUG]: "
labels: ["type::bug"]
body:
  - type: "dropdown"
    id: "version"
    attributes:
      label: "BlackArch version"
      description: |
        What version of BlackArch are you using?
      options:
        - "Please select a version."
        - "- BlackArch Linux 64 bit Full ISO 2023.04.01"
        - "- BlackArch Linux 64 bit Slim ISO 2023.05.01"
        - "- BlackArch Linux 64 bit Netinstall ISO 2023.04.01"
        - "- BlackArch Linux 64 bit OVA Image 2023.04.01"
        - "- BlackArch Linux Docker Image"
      default: 0
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Which environment or technology are you using?
      description: |
        Tell us which environment the issue is affecting. 
      options:
        - label: "Baremetal"
        - label: "VirtualBox Virtual Machine"
        - label: "VMware Virtual Machine"
        - label: "Hyper-V Virtual Machine"
        - label: "QEMU/KVM"
        - label: "Container"

  - type: input
    attributes:
      label: Kernel version
      description: |
        Please tell us what version of the Linux kernel you are using, or if you are using a custom kernel. 
        You can run `uname -r` if that command is available to you, or by running `cat /proc/version`.
      placeholder: "6.17.9-arch1-1"
    validations:
      required: false

  - type: "textarea"
    id: "description"
    attributes:
      label: "Describe the bug"
      description: "Please include a clear and concise description of what the issue is."
    validations:
      required: true

  - type: "textarea"
    id: "how-to-reproduce"
    attributes:
      label: "Steps to reproduce"
      description: "Please provide a step-by-step guide to reproduce this issue. Use concise, numbered bullet points so BlackArch developers can easily follow and replicate the problem."
    validations:
      required: true
